class UserAlreadyExistsError(Exception):
    """Raised when attempting to create a user that already exists"""
    pass 